### ISSUE TITLE
生成的Word 文档中 如何把请求报文和响应报文拿到？

### ISSUE THREAD

**Issue by ZerekZhang** [HanJunJun/Titan.Blog.WebAPP#6]
生成的Word 文档中 如何把请求报文和响应报文拿到，
![image](https://user-images.githubusercontent.com/16829343/93054520-08ba9c80-f69c-11ea-8f00-0db54da1df82.png)
或者如何能拿到  Example Value的值？

**Comment by hanjunjun** [comment]
建议看下swagger这项目的前端代码，去里面找找。
